2020-04-15 10:45:10,368 - INFO:  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-04-15 10:45:10,371 - INFO:  * Restarting with stat
2020-04-15 10:45:10,632 - WARNING:  * Debugger is active!
2020-04-15 10:45:10,634 - INFO:  * Debugger PIN: 240-917-717
2020-04-15 10:45:27,458 - INFO: 10.70.39.73 - - [15/Apr/2020 10:45:27] "[31m[1mGET /api/task/002/start HTTP/1.1[0m" 405 -
2020-04-15 10:45:31,962 - INFO: -----StartTask
2020-04-15 10:45:31,962 - ERROR: 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
2020-04-15 10:45:31,962 - ERROR: <class 'mysql.connector.errors.ProgrammingError'>
2020-04-15 10:45:31,963 - INFO: 10.70.39.73 - - [15/Apr/2020 10:45:31] "[37mPUT /api/task/002/start HTTP/1.1[0m" 200 -
2020-04-15 10:46:59,233 - INFO:  * Detected change in '/home/phale/workspace/ai-api-gp3-it2/resources/manager/tool/db.py', reloading
2020-04-15 10:46:59,263 - INFO:  * Restarting with stat
2020-04-15 10:46:59,526 - WARNING:  * Debugger is active!
2020-04-15 10:46:59,528 - INFO:  * Debugger PIN: 240-917-717
2020-04-15 10:47:11,983 - INFO: 10.70.39.73 - - [15/Apr/2020 10:47:11] "[37mPUT /api/task/002/start HTTP/1.1[0m" 200 -
2020-04-15 10:53:52,541 - INFO:  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
2020-04-15 10:53:52,542 - INFO:  * Restarting with stat
2020-04-15 10:53:52,803 - WARNING:  * Debugger is active!
2020-04-15 10:53:52,804 - INFO:  * Debugger PIN: 240-917-717
2020-04-15 10:54:08,893 - INFO:  * Detected change in '/home/phale/workspace/ai-api-gp3-it2/resources/manager/task_manager.py', reloading
2020-04-15 10:54:08,922 - INFO:  * Restarting with stat
2020-04-15 10:54:09,188 - WARNING:  * Debugger is active!
2020-04-15 10:54:09,188 - INFO:  * Debugger PIN: 240-917-717
2020-04-15 10:54:24,467 - INFO: 10.70.39.73 - - [15/Apr/2020 10:54:24] "[37mPUT /api/task/003/start HTTP/1.1[0m" 200 -
2020-04-15 10:54:55,917 - INFO: 10.70.39.73 - - [15/Apr/2020 10:54:55] "[35m[1mPUT /api/task/003/stop HTTP/1.1[0m" 500 -
